/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserDashboardRouteImport } from './routes/user/dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as UserRoundRoundIdRouteImport } from './routes/user/round/$roundId'
import { Route as AdminViolationsRoundIdRouteImport } from './routes/admin/violations.$roundId'
import { Route as AdminLeaderboardRoundIdRouteImport } from './routes/admin/leaderboard.$roundId'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UserRoundRoundIdRoute = UserRoundRoundIdRouteImport.update({
  id: '/round/$roundId',
  path: '/round/$roundId',
  getParentRoute: () => UserRouteRoute,
} as any)
const AdminViolationsRoundIdRoute = AdminViolationsRoundIdRouteImport.update({
  id: '/violations/$roundId',
  path: '/violations/$roundId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeaderboardRoundIdRoute = AdminLeaderboardRoundIdRouteImport.update({
  id: '/leaderboard/$roundId',
  path: '/leaderboard/$roundId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/admin/leaderboard/$roundId': typeof AdminLeaderboardRoundIdRoute
  '/admin/violations/$roundId': typeof AdminViolationsRoundIdRoute
  '/user/round/$roundId': typeof UserRoundRoundIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/admin/leaderboard/$roundId': typeof AdminLeaderboardRoundIdRoute
  '/admin/violations/$roundId': typeof AdminViolationsRoundIdRoute
  '/user/round/$roundId': typeof UserRoundRoundIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/admin/leaderboard/$roundId': typeof AdminLeaderboardRoundIdRoute
  '/admin/violations/$roundId': typeof AdminViolationsRoundIdRoute
  '/user/round/$roundId': typeof UserRoundRoundIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/user'
    | '/dashboard'
    | '/login'
    | '/todos'
    | '/admin/dashboard'
    | '/user/dashboard'
    | '/admin/leaderboard/$roundId'
    | '/admin/violations/$roundId'
    | '/user/round/$roundId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/user'
    | '/dashboard'
    | '/login'
    | '/todos'
    | '/admin/dashboard'
    | '/user/dashboard'
    | '/admin/leaderboard/$roundId'
    | '/admin/violations/$roundId'
    | '/user/round/$roundId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/user'
    | '/dashboard'
    | '/login'
    | '/todos'
    | '/admin/dashboard'
    | '/user/dashboard'
    | '/admin/leaderboard/$roundId'
    | '/admin/violations/$roundId'
    | '/user/round/$roundId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  TodosRoute: typeof TodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/user/round/$roundId': {
      id: '/user/round/$roundId'
      path: '/round/$roundId'
      fullPath: '/user/round/$roundId'
      preLoaderRoute: typeof UserRoundRoundIdRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/admin/violations/$roundId': {
      id: '/admin/violations/$roundId'
      path: '/violations/$roundId'
      fullPath: '/admin/violations/$roundId'
      preLoaderRoute: typeof AdminViolationsRoundIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/leaderboard/$roundId': {
      id: '/admin/leaderboard/$roundId'
      path: '/leaderboard/$roundId'
      fullPath: '/admin/leaderboard/$roundId'
      preLoaderRoute: typeof AdminLeaderboardRoundIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLeaderboardRoundIdRoute: typeof AdminLeaderboardRoundIdRoute
  AdminViolationsRoundIdRoute: typeof AdminViolationsRoundIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLeaderboardRoundIdRoute: AdminLeaderboardRoundIdRoute,
  AdminViolationsRoundIdRoute: AdminViolationsRoundIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserDashboardRoute: typeof UserDashboardRoute
  UserRoundRoundIdRoute: typeof UserRoundRoundIdRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserDashboardRoute: UserDashboardRoute,
  UserRoundRoundIdRoute: UserRoundRoundIdRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  TodosRoute: TodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
